# for dotfiles
export XDG_CONFIG_HOME="$HOME/.config"

# for specific data
export XDG_DATA_HOME="$XDG_CONFIG_HOME/local/share"

# for cached files
export XDG_CACHE_HOME="$XDG_CONFIG_HOME/cache"

# set default text editor
export EDITOR="nvim"
export VISUAL="nvim"

# dotfiles directory
export DOTFILES="$HOME/dotfiles"
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"

# zsh command history
export HISTFILE="$ZDOTDIR/.zhistory"
export HISTSIZE=10000
export SAVEHIST=10000

# use ripgrep in place of find for searching
export FZF_DEFAULT_COMMAND="rg --files --hidden --glob '!.git'"
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"

